title: Cinco Bola
description: Sua plataforma de marketplace universitário
email: eu@misterio.me
timezone: America/Sao_Paulo
exclude:
  - default.nix
  - gemset.nix
  - Gemfile
  - Gemfile.lock
sass:
  style: compact
collections:
  shops:
    light-color: "#dddddd"
    dark-color: "#333333"
    name: "Loja X"
    slug: "x"
    output: true
  products:
    name: "Camiseta"
    price: 19.00
    inventory: 10
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      inverted-nav-on-scroll: 100
  -
    scope:
      path: "README.md"
    values:
      permalink: "README"
      layout: cincobola
