title: Cinco Bola
email: eu@misterio.me
timezone: America/Sao_Paulo
exclude:
  - default.nix
  - gemset.nix
  - Gemfile
  - Gemfile.lock
sass:
  style: compact
defaults:
  -
    scope:
      path: "README.md"
    values:
      permalink: "README"
      layout: cincobola
